//
//  DemoStyleKit.cs
//  PaintCodeDemo
//
//  Created by Mike James on 06/03/2015.
//  Copyright (c) 2015 Xamarin Inc. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



using System;
using System.Drawing;
using Foundation;
using UIKit;
using CoreGraphics;

namespace PaintCodeDemo
{
    [Register ("DemoStyleKit")]
    public class DemoStyleKit : NSObject
    {

        //// Cache

        private static UIImage logo;

        //// Initialization

        static DemoStyleKit()
        {
            // Colors Initialization
            Purple = UIColor.FromRGBA(0.706f, 0.333f, 0.714f, 1.000f);
            Green = UIColor.FromRGBA(0.467f, 0.816f, 0.396f, 1.000f);

        }

        //// Colors

        public static UIColor Purple { get; private set; }
        public static UIColor Green { get; private set; }

        //// Images

        public static UIImage Logo
        {
            get
            {
                return logo ?? (logo = UIImage.FromFile("logo"));
            }
        }

        //// Drawing Methods

		public static void DrawTimer(CGRect frame, float percentage)
		{
			var context = UIGraphics.GetCurrentContext();

			var expression = 360.0f - percentage;

			var coverViewPath = UIBezierPath.FromOval(new CGRect(frame.GetMinX() + 5.0f, frame.GetMinY() + 4.0f, 230.0f, 230.0f));
			DemoStyleKit.Purple.SetFill();
			coverViewPath.Fill();


			context.SaveState();
			context.TranslateCTM(frame.GetMinX() + 120.0f, frame.GetMinY() + 119.0f);
			context.RotateCTM(-90.0f * NMath.PI / 180.0f);

			var completedViewRect = new CGRect(-115.0f, -115.0f, 230.0f, 230.0f);
			var completedViewPath = new UIBezierPath();
			completedViewPath.AddArc(new CGPoint(completedViewRect.GetMidX(), completedViewRect.GetMidY()), completedViewRect.Width / 2.0f, (nfloat)(-360.0f * NMath.PI/180), (nfloat)(-expression * NMath.PI/180.0f), true);
			completedViewPath.AddLineTo(new CGPoint(completedViewRect.GetMidX(), completedViewRect.GetMidY()));
			completedViewPath.ClosePath();

			DemoStyleKit.Green.SetFill();
			completedViewPath.Fill();

			context.RestoreState();

			var backgroundViewPath = UIBezierPath.FromOval(new CGRect(frame.GetMinX() + 10.0f, frame.GetMinY() + 9.0f, 220.0f, 220.0f));
			DemoStyleKit.Purple.SetFill();
			backgroundViewPath.Fill();
		}


    }
}
